use std::fs;
use std::path::Path;

fn main() {
    // Emit a tiny JSON blob into the bundled frontend dir so the topbar
    // version chip has a guaranteed-fresh source even when /api/config
    // fails (stale running binary, mid-restart, offline web mode, etc.).
    // CARGO_PKG_VERSION is baked from workspace.package.version, so this
    // file always reflects the workspace version at *build* time —
    // single-source from Cargo.toml.
    let ver = env!("CARGO_PKG_VERSION");

    // Emit version.json (asynchronous fetch fallback).
    let json_path = Path::new("../frontend/version.json");
    if let Err(e) = fs::write(json_path, format!("{{\"version\":\"{ver}\"}}\n")) {
        println!("cargo:warning=failed to write {}: {e}", json_path.display());
    }

    // Emit _version.js — loaded synchronously before app.js via a
    // <script> tag in index.html, so the version chip resolves before
    // any fetch happens. Survives /api/config and version.json fetch
    // failures entirely.
    let js_path = Path::new("../frontend/_version.js");
    let js_body = format!(
        "/* generated by src-tauri/build.rs — single-source: workspace.package.version */\n\
         window.__TRADERVIEW_VERSION__ = \"{ver}\";\n"
    );
    if let Err(e) = fs::write(js_path, js_body) {
        println!("cargo:warning=failed to write {}: {e}", js_path.display());
    }
    // Rebuild whenever the version source changes.
    println!("cargo:rerun-if-changed=../Cargo.toml");

    tauri_build::build()
}
