// i18n_dnt.mjs — proper-noun protection for the i18n translator.
//
// Two responsibilities:
//   1. `isDnt(key, value)` — true when the entire value should be left
//      verbatim in every locale: key paths matching broker/engine
//      patterns, OR a value that is essentially nothing but proper
//      nouns once you strip them out.
//   2. `maskProperNouns(value)` — replace every occurrence of a known
//      proper noun with an opaque sentinel (`__PN0__`, `__PN1__`, …)
//      so the translator can render the surrounding text without
//      mangling brand names. Returns the masked string plus a back-map
//      the caller uses to restore.
//
// The proper-noun list is loaded from `frontend/i18n/proper_nouns.txt`
// (generated by `i18n_extract_proper_nouns.mjs`, hand-edited as needed).
// Each line is a literal term. Sorted longest-first so multi-word
// matches like "Charles Schwab" bind before "Schwab".

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const LIST_PATH = resolve(__dirname, '../i18n/proper_nouns.txt');

function loadList() {
    let raw;
    try {
        raw = readFileSync(LIST_PATH, 'utf8');
    } catch (e) {
        if (e.code === 'ENOENT') return [];
        throw e;
    }
    return raw
        .split('\n')
        .map((l) => l.replace(/\r$/, ''))
        .filter((l) => l.length > 0 && !l.startsWith('#'));
}

const PROPER_NOUNS = loadList();

// Pre-build a single big regex that matches any proper noun. Sorted
// longest-first so the engine picks the longest match first.
function escapeForRegex(s) {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
const NOUN_RE = PROPER_NOUNS.length
    ? new RegExp(
        '(?:' +
            PROPER_NOUNS.map(escapeForRegex).join('|') +
            ')',
        'g',
    )
    : null;

// Key paths whose values are *always* labels for a fixed identifier —
// e.g. broker dropdown options, engine selectors. The value should
// stay verbatim regardless of what it looks like.
const KEY_PATTERNS = [
    /\.accounts?\.opt\./i,
    /\.broker(s|_)?\./i,
    /\.exchange(s|_)?\.opt\./i,
    /\.vendor\./i,
    /\.symbol\.opt\./i,
    /\.engine\./i,
    /\.tool\./i,
    /\.product\./i,
    /\.cmd\./i,
    /\.framework\./i,
    /\.os\.opt\./i,
];

/**
 * Replace each proper-noun occurrence in `value` with an opaque ASCII
 * sentinel. Returns `{ masked, back }` where `back` maps each sentinel
 * back to the original term — feed `back` to the caller's restore step.
 *
 * Sentinels deliberately use a different prefix from `{token}`-style
 * interpolation placeholders (`__TVI…__`) so the two systems compose.
 */
export function maskProperNouns(value) {
    if (!NOUN_RE || typeof value !== 'string' || value.length === 0) {
        return { masked: value, back: new Map() };
    }
    const back = new Map();
    let next = 0;
    const masked = value.replace(NOUN_RE, (m) => {
        const sentinel = `__PN${next++}__`;
        back.set(sentinel, m);
        return sentinel;
    });
    return { masked, back };
}

/**
 * True when the value should not be translated at all (the translator
 * will skip it). The rule is conservative: only return true when
 *   (a) the key path is in the dropdown/identifier allowlist, OR
 *   (b) stripping all proper nouns from the value leaves essentially
 *       no translatable text (≤ 2 alphabetic chars).
 *
 * "Compute BOP" survives both tests — it has translatable text around
 * the proper noun, so it goes through translation with "BOP" masked.
 * "E*TRADE" doesn't survive — stripping the proper noun leaves nothing.
 */
export function isDnt(key, value) {
    if (typeof value !== 'string') return false;
    if (KEY_PATTERNS.some((re) => re.test(key))) return true;
    if (!NOUN_RE) return false;
    const stripped = value.replace(NOUN_RE, '');
    const alphaLeft = stripped.replace(/[^A-Za-z]/g, '').length;
    return alphaLeft <= 2;
}

export const _properNounCount = PROPER_NOUNS.length;
