//! IRC §465 — Deductions limited to amount at risk.
//!
//! Pairs with `section_469` (passive activity losses) to complete the
//! loss-limitation framework. §465 applies first (limits to amount at
//! risk), then §469 applies (limits by passive activity character).
//! Critical for any trader, partner, or S corp shareholder with
//! leveraged positions.
//!
//! **§465(a) general rule**: deductible loss from an activity is
//! limited to the amount the taxpayer has "at risk" in that activity
//! at the close of the taxable year.
//!
//! **§465(b) amount at risk includes:**
//!
//!   - **§465(b)(1)(A)**: cash + adjusted basis of property contributed
//!   - **§465(b)(1)(B)**: amounts borrowed for use in the activity for
//!     which the taxpayer is personally liable (recourse debt)
//!   - **§465(b)(2)**: amounts borrowed to the extent the taxpayer has
//!     pledged property as security (only the FMV of the pledged
//!     property, NOT including property used in the activity itself)
//!
//! **§465(b)(4) general nonrecourse exclusion**: a taxpayer is NOT at
//! risk with respect to amounts protected against loss through
//! nonrecourse financing, guarantees, stop-loss agreements, or other
//! similar arrangements.
//!
//! **§465(b)(6) qualified nonrecourse financing carve-out** (THE
//! load-bearing real-property exception): for the activity of holding
//! real property, a taxpayer's share of qualified nonrecourse financing
//! secured by real property is treated as AT RISK even though the
//! taxpayer is not personally liable. Requires:
//!   - Financing borrowed with respect to real property activity
//!   - From a qualified person (commercial lender, government, or
//!     government-guaranteed) — NOT a related-party seller
//!   - Not convertible debt
//!   - Secured by real property (incidental property < 10% FMV
//!     disregarded)
//!
//! **§465(b)(3) related-party limitation**: borrowing from a person
//! with an interest in the activity (related party) reduces the at-risk
//! amount — these aren't "real" risk because the related party isn't
//! likely to enforce collection.
//!
//! **§465(d) suspended losses**: any loss disallowed under §465(a)
//! carries forward indefinitely to be deducted in a subsequent year
//! when sufficient at-risk amount exists.
//!
//! **§465(e) recapture**: if a taxpayer's at-risk amount goes negative
//! (e.g., distribution of leveraged capital), prior losses claimed up
//! to that negative amount are recaptured as income in the year the
//! amount went negative.

use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActivityKind {
    /// Real property activity (rental, development, holding). Eligible
    /// for §465(b)(6) qualified nonrecourse financing carve-out.
    RealPropertyHolding,
    /// Trade or business activity other than real property. No
    /// nonrecourse carve-out.
    OtherTradeOrBusiness,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Section465Input {
    pub activity_kind: ActivityKind,
    /// Loss generated by the activity this year (positive number — the
    /// gross loss before §465 limitation).
    pub activity_loss_this_year: Decimal,
    /// Cash + adjusted basis of property contributed (§465(b)(1)(A)).
    pub cash_and_basis_contributed: Decimal,
    /// Amounts borrowed for the activity for which taxpayer is
    /// personally liable (§465(b)(1)(B)) — recourse debt.
    pub recourse_debt: Decimal,
    /// FMV of property pledged as security that is NOT used in the
    /// activity itself (§465(b)(2)).
    pub external_pledged_property_fmv: Decimal,
    /// Qualified nonrecourse financing — only at risk under §465(b)(6)
    /// for real property activities.
    pub qualified_nonrecourse_financing: Decimal,
    /// General nonrecourse debt that is NOT qualified (§465(b)(4)
    /// exclusion). Never at risk.
    pub other_nonrecourse_debt: Decimal,
    /// Amounts borrowed from related parties with an interest in the
    /// activity — §465(b)(3) reduces at-risk amount.
    pub related_party_borrowing: Decimal,
    /// Prior-year suspended losses carrying forward under §465(d).
    pub prior_year_suspended_loss: Decimal,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Section465Result {
    /// Amount at risk before applying current-year loss.
    pub amount_at_risk_before_loss: Decimal,
    /// Total loss claimed this year = min(activity_loss + prior_carryover,
    /// amount_at_risk_before_loss).
    pub loss_allowed_this_year: Decimal,
    /// Amount carried forward to next year under §465(d).
    pub loss_suspended_carryover: Decimal,
    /// Amount at risk after the allowed loss reduces it (§465(b)(5)
    /// adjustment).
    pub amount_at_risk_after_loss: Decimal,
    /// True if at-risk went or would go negative (triggering §465(e)
    /// recapture).
    pub negative_at_risk_recapture_triggered: bool,
    /// True if the §465(b)(6) qualified nonrecourse carve-out was
    /// available (real-property activity) and contributed to at-risk.
    pub qualified_nonrecourse_carveout_applied: bool,
    pub note: String,
}

pub fn compute(input: &Section465Input) -> Section465Result {
    // §465(b)(1)(A): cash + basis contributed.
    let contributed = input.cash_and_basis_contributed;

    // §465(b)(1)(B): recourse debt.
    let recourse = input.recourse_debt;

    // §465(b)(2): external pledged property (separate from activity property).
    let pledged = input.external_pledged_property_fmv;

    // §465(b)(6): qualified nonrecourse financing for real property
    // activities only.
    let carveout_applied = matches!(input.activity_kind, ActivityKind::RealPropertyHolding)
        && input.qualified_nonrecourse_financing > Decimal::ZERO;
    let qnf_at_risk = if carveout_applied {
        input.qualified_nonrecourse_financing
    } else {
        Decimal::ZERO
    };

    // §465(b)(3): related-party borrowing reduces at-risk amount.
    let related_party_reduction = input.related_party_borrowing;

    // Total at-risk before applying current-year loss. Clamp at zero.
    let pre_loss_at_risk = (contributed + recourse + pledged + qnf_at_risk
        - related_party_reduction)
        .max(Decimal::ZERO);

    // Loss to absorb = current year + prior carryover.
    let total_potential_loss = input.activity_loss_this_year + input.prior_year_suspended_loss;
    let allowed = total_potential_loss.min(pre_loss_at_risk);
    let suspended_carryover = (total_potential_loss - allowed).max(Decimal::ZERO);
    let post_loss_at_risk = (pre_loss_at_risk - allowed).max(Decimal::ZERO);

    // §465(e) recapture flag — set if either:
    //   (a) the allowed loss would have made at-risk negative without
    //       the §465(a) cap, OR
    //   (b) the at-risk amount before subtracting related-party
    //       borrowing was negative (unusual but possible).
    let recapture_triggered =
        (contributed + recourse + pledged + qnf_at_risk - related_party_reduction) < Decimal::ZERO;

    let note = if recapture_triggered {
        format!(
            "§465(e) recapture triggered — at-risk amount went negative; prior losses ${} subject to recapture as income",
            (-(contributed + recourse + pledged + qnf_at_risk - related_party_reduction))
                .round_dp(2)
        )
    } else if suspended_carryover > Decimal::ZERO {
        format!(
            "§465(a) limit: ${} loss allowed (at-risk ${} after reduction); ${} suspended under §465(d) for future at-risk{}",
            allowed.round_dp(2),
            pre_loss_at_risk.round_dp(2),
            suspended_carryover.round_dp(2),
            if carveout_applied {
                " (§465(b)(6) QNF carve-out applied)"
            } else {
                ""
            }
        )
    } else {
        format!(
            "§465(a) limit satisfied: ${} loss fully allowed (at-risk ${} before, ${} after){}",
            allowed.round_dp(2),
            pre_loss_at_risk.round_dp(2),
            post_loss_at_risk.round_dp(2),
            if carveout_applied {
                " (§465(b)(6) QNF carve-out applied)"
            } else {
                ""
            }
        )
    };

    Section465Result {
        amount_at_risk_before_loss: pre_loss_at_risk,
        loss_allowed_this_year: allowed,
        loss_suspended_carryover: suspended_carryover,
        amount_at_risk_after_loss: post_loss_at_risk,
        negative_at_risk_recapture_triggered: recapture_triggered,
        qualified_nonrecourse_carveout_applied: carveout_applied,
        note,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rust_decimal_macros::dec;

    fn base() -> Section465Input {
        Section465Input {
            activity_kind: ActivityKind::OtherTradeOrBusiness,
            activity_loss_this_year: dec!(50_000),
            cash_and_basis_contributed: dec!(20_000),
            recourse_debt: dec!(40_000),
            external_pledged_property_fmv: Decimal::ZERO,
            qualified_nonrecourse_financing: Decimal::ZERO,
            other_nonrecourse_debt: Decimal::ZERO,
            related_party_borrowing: Decimal::ZERO,
            prior_year_suspended_loss: Decimal::ZERO,
        }
    }

    #[test]
    fn cash_plus_recourse_debt_at_risk_full_loss_allowed() {
        // $20k cash + $40k recourse = $60k at risk. Loss $50k → full
        // allowance. Post-loss at-risk = $10k.
        let r = compute(&base());
        assert_eq!(r.amount_at_risk_before_loss, dec!(60_000));
        assert_eq!(r.loss_allowed_this_year, dec!(50_000));
        assert_eq!(r.loss_suspended_carryover, Decimal::ZERO);
        assert_eq!(r.amount_at_risk_after_loss, dec!(10_000));
    }

    #[test]
    fn loss_exceeds_at_risk_partial_allowance_and_suspension() {
        // At-risk $60k, loss $100k → $60k allowed, $40k suspended.
        let mut i = base();
        i.activity_loss_this_year = dec!(100_000);
        let r = compute(&i);
        assert_eq!(r.loss_allowed_this_year, dec!(60_000));
        assert_eq!(r.loss_suspended_carryover, dec!(40_000));
        assert_eq!(r.amount_at_risk_after_loss, Decimal::ZERO);
    }

    #[test]
    fn prior_year_carryover_added_to_current_loss() {
        // $50k current loss + $30k prior carryover = $80k total. At-risk
        // $60k → $60k allowed, $20k suspended.
        let mut i = base();
        i.prior_year_suspended_loss = dec!(30_000);
        let r = compute(&i);
        assert_eq!(r.loss_allowed_this_year, dec!(60_000));
        assert_eq!(r.loss_suspended_carryover, dec!(20_000));
    }

    #[test]
    fn nonrecourse_debt_not_at_risk_in_non_real_property_activity() {
        // §465(b)(4): general nonrecourse debt not at risk. Even with
        // $100k nonrecourse, at-risk stays at $60k (cash + recourse).
        let mut i = base();
        i.other_nonrecourse_debt = dec!(100_000);
        let r = compute(&i);
        assert_eq!(r.amount_at_risk_before_loss, dec!(60_000));
    }

    #[test]
    fn qualified_nonrecourse_real_property_section_465b6_applies() {
        // §465(b)(6): real-property activity with QNF is at risk.
        // $20k cash + $40k recourse + $200k QNF = $260k at risk.
        // Loss $50k → full allowance.
        let mut i = base();
        i.activity_kind = ActivityKind::RealPropertyHolding;
        i.qualified_nonrecourse_financing = dec!(200_000);
        let r = compute(&i);
        assert_eq!(r.amount_at_risk_before_loss, dec!(260_000));
        assert!(r.qualified_nonrecourse_carveout_applied);
        assert!(r.note.contains("§465(b)(6)"));
    }

    #[test]
    fn qualified_nonrecourse_not_applied_for_non_real_property() {
        // §465(b)(6) is real-property-only. For other trade or business,
        // QNF doesn't get the carve-out.
        let mut i = base();
        i.activity_kind = ActivityKind::OtherTradeOrBusiness;
        i.qualified_nonrecourse_financing = dec!(200_000);
        let r = compute(&i);
        assert_eq!(r.amount_at_risk_before_loss, dec!(60_000)); // QNF not added
        assert!(!r.qualified_nonrecourse_carveout_applied);
    }

    #[test]
    fn external_pledged_property_increases_at_risk() {
        // §465(b)(2): external pledged property FMV is at risk.
        let mut i = base();
        i.external_pledged_property_fmv = dec!(30_000);
        let r = compute(&i);
        assert_eq!(r.amount_at_risk_before_loss, dec!(90_000)); // 60 + 30
    }

    #[test]
    fn related_party_borrowing_reduces_at_risk() {
        // §465(b)(3): related-party borrowing reduces at-risk.
        let mut i = base();
        i.related_party_borrowing = dec!(20_000);
        let r = compute(&i);
        // 20 cash + 40 recourse - 20 related = 40.
        assert_eq!(r.amount_at_risk_before_loss, dec!(40_000));
    }

    #[test]
    fn zero_at_risk_no_loss_allowed() {
        // No contributions, no recourse, no QNF. At-risk = 0. All loss
        // suspended.
        let mut i = base();
        i.cash_and_basis_contributed = Decimal::ZERO;
        i.recourse_debt = Decimal::ZERO;
        let r = compute(&i);
        assert_eq!(r.amount_at_risk_before_loss, Decimal::ZERO);
        assert_eq!(r.loss_allowed_this_year, Decimal::ZERO);
        assert_eq!(r.loss_suspended_carryover, dec!(50_000));
    }

    #[test]
    fn negative_at_risk_recapture_triggered() {
        // Pathological: related-party borrowing exceeds positive
        // components → at-risk would be negative without clamp.
        // §465(e) recapture triggers.
        let mut i = base();
        i.cash_and_basis_contributed = dec!(10_000);
        i.recourse_debt = dec!(10_000);
        i.related_party_borrowing = dec!(50_000); // exceeds
        let r = compute(&i);
        assert!(r.negative_at_risk_recapture_triggered);
        assert_eq!(r.amount_at_risk_before_loss, Decimal::ZERO); // clamped
        assert!(r.note.contains("§465(e)"));
    }

    #[test]
    fn exact_at_risk_match_full_allowance_zero_remaining() {
        // At-risk $60k, loss $60k → full allowance, $0 remaining
        // at-risk, $0 suspended.
        let mut i = base();
        i.activity_loss_this_year = dec!(60_000);
        let r = compute(&i);
        assert_eq!(r.loss_allowed_this_year, dec!(60_000));
        assert_eq!(r.amount_at_risk_after_loss, Decimal::ZERO);
        assert_eq!(r.loss_suspended_carryover, Decimal::ZERO);
    }

    #[test]
    fn qnf_carryover_real_estate_partner_full_at_risk() {
        // Real estate partnership: $50k cash + $0 recourse + $1M QNF.
        // Loss $200k → full allowance. At-risk after = $850k.
        let mut i = base();
        i.activity_kind = ActivityKind::RealPropertyHolding;
        i.cash_and_basis_contributed = dec!(50_000);
        i.recourse_debt = Decimal::ZERO;
        i.qualified_nonrecourse_financing = dec!(1_000_000);
        i.activity_loss_this_year = dec!(200_000);
        let r = compute(&i);
        assert_eq!(r.amount_at_risk_before_loss, dec!(1_050_000));
        assert_eq!(r.loss_allowed_this_year, dec!(200_000));
        assert_eq!(r.amount_at_risk_after_loss, dec!(850_000));
    }

    #[test]
    fn qnf_does_not_apply_when_other_trade_uses_real_estate_lookup() {
        // ActivityKind::OtherTradeOrBusiness explicitly disables the
        // §465(b)(6) carve-out even with QNF input. Pinned because the
        // activity classification is the gatekeeper.
        let mut i = base();
        i.activity_kind = ActivityKind::OtherTradeOrBusiness;
        i.qualified_nonrecourse_financing = dec!(500_000);
        let r = compute(&i);
        assert!(!r.qualified_nonrecourse_carveout_applied);
        // At-risk unchanged from base.
        assert_eq!(r.amount_at_risk_before_loss, dec!(60_000));
    }

    #[test]
    fn complex_combination_partnership_real_estate_with_all_components() {
        // Real estate partnership combining all at-risk components:
        // $30k cash + $20k recourse + $50k external pledged + $500k QNF
        // - $10k related-party = $590k at-risk.
        let mut i = base();
        i.activity_kind = ActivityKind::RealPropertyHolding;
        i.cash_and_basis_contributed = dec!(30_000);
        i.recourse_debt = dec!(20_000);
        i.external_pledged_property_fmv = dec!(50_000);
        i.qualified_nonrecourse_financing = dec!(500_000);
        i.related_party_borrowing = dec!(10_000);
        let r = compute(&i);
        assert_eq!(r.amount_at_risk_before_loss, dec!(590_000));
        assert!(r.qualified_nonrecourse_carveout_applied);
    }

    #[test]
    fn prior_carryover_alone_suspended_when_no_current_year_at_risk() {
        // No current loss but $30k prior carryover. At-risk $60k →
        // $30k of carryover absorbed, $0 remaining suspended.
        let mut i = base();
        i.activity_loss_this_year = Decimal::ZERO;
        i.prior_year_suspended_loss = dec!(30_000);
        let r = compute(&i);
        assert_eq!(r.loss_allowed_this_year, dec!(30_000));
        assert_eq!(r.loss_suspended_carryover, Decimal::ZERO);
        assert_eq!(r.amount_at_risk_after_loss, dec!(30_000));
    }

    #[test]
    fn prior_carryover_partial_when_combined_loss_exceeds_at_risk() {
        // Current $50k + prior $30k = $80k loss. At-risk $60k → $60k
        // allowed, $20k suspended.
        let mut i = base();
        i.prior_year_suspended_loss = dec!(30_000);
        let r = compute(&i);
        assert_eq!(r.loss_allowed_this_year, dec!(60_000));
        assert_eq!(r.loss_suspended_carryover, dec!(20_000));
    }

    #[test]
    fn zero_loss_no_op() {
        let mut i = base();
        i.activity_loss_this_year = Decimal::ZERO;
        let r = compute(&i);
        assert_eq!(r.loss_allowed_this_year, Decimal::ZERO);
        assert_eq!(r.amount_at_risk_after_loss, dec!(60_000));
    }

    #[test]
    fn very_large_loss_no_precision_loss_explicit_recourse_zero() {
        // Cleaner: zero recourse so the totals are pure billions.
        let mut i = base();
        i.activity_kind = ActivityKind::RealPropertyHolding;
        i.cash_and_basis_contributed = dec!(1_000_000_000);
        i.recourse_debt = Decimal::ZERO;
        i.qualified_nonrecourse_financing = dec!(5_000_000_000);
        i.activity_loss_this_year = dec!(800_000_000);
        let r = compute(&i);
        assert_eq!(r.amount_at_risk_before_loss, dec!(6_000_000_000));
        assert_eq!(r.loss_allowed_this_year, dec!(800_000_000));
    }

    #[test]
    fn note_describes_recapture_path() {
        let mut i = base();
        i.cash_and_basis_contributed = Decimal::ZERO;
        i.recourse_debt = Decimal::ZERO;
        i.related_party_borrowing = dec!(50_000);
        let r = compute(&i);
        assert!(r.note.contains("recapture"));
    }

    #[test]
    fn note_describes_qnf_carveout_when_applied() {
        let mut i = base();
        i.activity_kind = ActivityKind::RealPropertyHolding;
        i.qualified_nonrecourse_financing = dec!(100_000);
        let r = compute(&i);
        assert!(r.note.contains("QNF carve-out") || r.note.contains("§465(b)(6)"));
    }

    #[test]
    fn note_for_suspended_loss_mentions_section_465d() {
        let mut i = base();
        i.activity_loss_this_year = dec!(100_000); // exceeds 60k at-risk
        let r = compute(&i);
        assert!(r.note.contains("§465(d)"));
    }
}
